name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        options: > 
          --health-cmd="mysqladmin ping --silent" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3
        env:
          MYSQL_ROOT_PASSWORD: root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Wait for MySQL to be ready
        run: sleep 30

      - name: Prepare database for integration tests
        run: |
          mysql -h127.0.0.1 -uroot -proot < sql/create-db.sql
          mvn --batch-mode --update-snapshots datanucleus:enhance datanucleus:schema-create

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        working-directory: lodgify

      - name: Run tests
        run: mvn test
        working-directory: lodgify
