name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Clean and compile the project
        run: |
          cd lodgify
          mvn --batch-mode clean compile

      - name: Prepare database for testing
        run: | 
          sudo /etc/init.d/mysql start
          cd lodgify
          mysql -uroot -proot < sql/create-db.sql
          mvn --batch-mode --update-snapshots datanucleus:enhance datanucleus:schema-create

      - name: Start the server in the background
        run: |
          cd lodgify
          mvn --batch-mode jetty:run &
          sleep 10

      - name: Run the unit tests
        run: |
          cd lodgify
          mvn test

      - name: Execute integration tests
        run: |
          cd lodgify
          mvn --batch-mode --update-snapshots verify -Pintegration-tests

      - name: Execute performance tests
        run: |
          cd lodgify
          mvn --batch-mode --update-snapshots verify -Pperformance-tests
