name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify SQL file exists
        run: |
          if [ ! -f lodgify/sql/create-db.sql ]; then
            echo "SQL file not found!"
            exit 1
          fi

      - name: Prepare database for integration tests
        run: |
          sudo /etc/init.d/mysql start
          mysql -uroot -proot < lodgify/sql/create-db.sql
          mvn --batch-mode --update-snapshots datanucleus:enhance datanucleus:schema-create
        working-directory: lodgify

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
        working-directory: lodgify

      - name: Run tests
        run: mvn test
        working-directory: lodgify
